In [1]:
import time
import datetime
from matplotlib import pyplot
from pyspark.sql.functions import lit,unix_timestamp,col,concat

In [2]:
sqlContext=SQLContext(spark.sparkContext)
raw_meter_data = sqlContext.read.format("org.apache.spark.sql.cassandra").options(table="meter_data", keyspace="tangez_staging").load()
raw_meter_data.toPandas()

,meter_data_id,checksum,consumption_data,encoder_tamper,ert_id_ls_bits,ert_id_ms_bits,ert_type,physical_tamper,preamble,received_ts,reserved,sync_bit
0,53426,47498238489494848,1308,None,100000000000000000000081,53,electric,None,0xF2A60,2018-12-28 11:00:00,None,1
1,47916,47498238489494848,1710,None,100000000000000000000056,47,electric,None,0xF2A60,2018-12-28 11:30:00,None,1
2,12886,47498238489494848,2405,None,100000000000000000000002,12,electric,None,0xF2A60,2018-12-28 11:00:00,None,1
3,19838,47498238489494848,388,None,100000000000000000000085,19,electric,None,0xF2A60,2018-12-28 11:45:00,None,1
4,2246,47498238489494848,2423,None,100000000000000000000079,22,electric,None,0xF2A60,2018-12-28 11:00:00,None,1
5,26966,47498238489494848,864,None,100000000000000000000041,26,electric,None,0xF2A60,2018-12-28 11:15:00,None,1
6,50204,47498238489494848,2506,None,100000000000000000000071,50,electric,None,0xF2A60,2018-12-28 11:15:00,None,1
7,24822,47498238489494848,2207,None,100000000000000000000047,24,electric,None,0xF2A60,2018-12-28 11:00:00,None,1
8,105,47498238489494848,3606,None,100000000000000000000075,10,electric,None,0xF2A60,2018-12-28 11:45:00,None,1
9,26550,47498238489494848,2313,None,100000000000000000000055,26,electric,None,0xF2A60,2018-12-28 11:30:00,None,1
10,21427,47498238489494848,2644,None,100000000000000000000094,21,electric,None,0xF2A60,2018-12-28 11:45:00,None,1
11,5552,47498238489494848,56,None,100000000000000000000062,55,electric,None,0xF2A60,2018-12-28 11:00:00,None,1
12,78465,47498238489494848,2248,None,100000000000000000000047,78,electric,None,0xF2A60,2018-12-28 11:45:00,None,1
13,33109,47498238489494848,1633,None,100000000000000000000063,33,electric,None,0xF2A60,2018-12-28 11:45:00,None,1
14,94846,47498238489494848,1270,None,100000000000000000000096,94,electric,None,0xF2A60,2018-12-28 11:30:00,None,1
15,47187,47498238489494848,3995,None,100000000000000000000043,47,electric,None,0xF2A60,2018-12-28 11:00:00,None,1
16,53800,47498238489494848,3498,None,100000000000000000000045,53,electric,None,0xF2A60,2018-12-28 11:00:00,None,1
17,85626,47498238489494848,1959,None,100000000000000000000000,85,electric,None,0xF2A60,2018-12-28 11:15:00,None,1
18,33477,47498238489494848,656,None,100000000000000000000018,33,electric,None,0xF2A60,2018-12-28 11:30:00,None,1
19,35562,47498238489494848,1480,None,100000000000000000000100,35,electric,None,0xF2A60,2018-12-28 11:30:00,None,1
20,85887,47498238489494848,3855,None,100000000000000000000027,85,electric,None,0xF2A60,2018-12-28 11:15:00,None,1
21,25543,47498238489494848,3607,None,100000000000000000000073,25,electric,None,0xF2A60,2018-12-28 11:15:00,None,1
22,8690,47498238489494848,2297,None,100000000000000000000017,86,electric,None,0xF2A60,2018-12-28 11:30:00,None,1
23,16484,47498238489494848,1306,None,100000000000000000000044,16,electric,None,0xF2A60,2018-12-28 11:45:00,None,1
24,85623,47498238489494848,1870,None,100000000000000000000013,85,electric,None,0xF2A60,2018-12-28 11:45:00,None,1
25,14334,47498238489494848,2275,None,100000000000000000000032,14,electric,None,0xF2A60,2018-12-28 11:00:00,None,1
26,37691,47498238489494848,1150,None,100000000000000000000047,37,electric,None,0xF2A60,2018-12-28 11:00:00,None,1
27,83461,47498238489494848,607,None,100000000000000000000039,83,electric,None,0xF2A60,2018-12-28 11:15:00,None,1
28,4630,47498238489494848,3599,None,100000000000000000000008,46,electric,None,0xF2A60,2018-12-28 11:45:00,None,1
29,17262,47498238489494848,526,None,100000000000000000000095,17,electric,None,0xF2A60,2018-12-28 11:45:00,None,1
...,...,...,...,...,...,...,...,...,...,...,...,...
3889,71545,47498238489494848,1171,None,100000000000000000000036,71,electric,None,0xF2A60,2018-12-28 11:15:00,None,1
3890,6642,47498238489494848,1687,None,100000000000000000000031,66,electric,None,0xF2A60,2018-12-28 11:00:00,None,1
3891,4219,47498238489494848,1783,None,100000000000000000000072,42,electric,None,0xF2A60,2018-12-28 11:30:00,None,1
3892,44836,47498238489494848,2038,None,100000000000000000000055,44,electric,None,0xF2A60,2018-12-28 11:00:00,None,1
3893,55480,47498238489494848,2935,None,100000000000000000000070,55,electric,None,0xF2A60,2018-12-28 11:00:00,None,1
3894,5266,47498238489494848,736,None,100000000000000000000038,52,electric,None,0xF2A60,2018-12-28 11:00:00,None,1
3895,69257,47498238489494848,1854,None,100000000000000000000043,69,electric,None,0xF2A60,2018-12-28 11:30:00,None,1
3896,68143,47498238489494848,3633,None,100000000000000000000013,68,electric,None,0xF2A60,2018-12-28 11:00:00,None,1
3897,75308,47498238489494848,531,None,100000000000000000000014,75,electric,None,0xF2A60,2018-12-28 11:00:00,None,1
3898,92669,47498238489494848,1408,None,100000000000000000000083,92,electric,None,0xF2A60,2018-12-28 11:15:00,None,1
3899,22820,47498238489494848,860,None,100000000000000000000032,22,electric,None,0xF2A60,2018-12-28 11:00:00,None,1
3900,29314,47498238489494848,333,None,100000000000000000000064,29,electric,None,0xF2A60,2018-12-28 11:00:00,None,1
3901,23980,47498238489494848,1108,None,100000000000000000000082,23,electric,None,0xF2A60,2018-12-28 11:30:00,None,1
3902,34974,47498238489494848,3537,None,100000000000000000000097,34,electric,None,0xF2A60,2018-12-28 11:30:00,None,1
3903,54511,47498238489494848,1711,None,100000000000000000000025,54,electric,None,0xF2A60,2018-12-28 11:45:00,None,1
3904,89581,47498238489494848,1163,None,100000000000000000000020,89,electric,None,0xF2A60,2018-12-28 11:00:00,None,1
3905,77917,47498238489494848,3384,None,100000000000000000000077,77,electric,None,0xF2A60,2018-12-28 11:30:00,None,1
3906,88512,47498238489494848,2955,None,100000000000000000000057,88,electric,None,0xF2A60,2018-12-28 11:45:00,None,1
3907,63412,47498238489494848,2319,None,100000000000000000000023,63,electric,None,0xF2A60,2018-12-28 11:30:00,None,1
3908,1683,47498238489494848,536,None,100000000000000000000099,16,electric,None,0xF2A60,2018-12-28 11:45:00,None,1
3909,31975,47498238489494848,605,None,100000000000000000000014,31,electric,None,0xF2A60,2018-12-28 11:45:00,None,1
3910,58355,47498238489494848,2650,None,100000000000000000000073,58,electric,None,0xF2A60,2018-12-28 11:00:00,None,1
3911,55787,47498238489494848,3690,None,100000000000000000000087,55,electric,None,0xF2A60,2018-12-28 11:00:00,None,1
3912,45685,47498238489494848,317,None,100000000000000000000013,45,electric,None,0xF2A60,2018-12-28 11:45:00,None,1
3913,96911,47498238489494848,683,None,100000000000000000000033,96,electric,None,0xF2A60,2018-12-28 11:15:00,None,1
3914,39788,47498238489494848,683,None,100000000000000000000066,39,electric,None,0xF2A60,2018-12-28 11:45:00,None,1
3915,43379,47498238489494848,264,None,100000000000000000000017,43,electric,None,0xF2A60,2018-12-28 11:15:00,None,1
3916,26777,47498238489494848,2551,None,100000000000000000000029,26,electric,None,0xF2A60,2018-12-28 11:30:00,None,1
3917,55683,47498238489494848,3595,None,100000000000000000000091,55,electric,None,0xF2A60,2018-12-28 11:15:00,None,1
3918,40602,47498238489494848,3753,None,100000000000000000000033,40,electric,None,0xF2A60,2018-12-28 11:15:00,None,1

In [8]:
raw_customer_data = sqlContext.read.format("org.apache.spark.sql.cassandra").options(table="customer_data", keyspace="tangez_staging").load()
raw_customer_data.toPandas()

,ert_id,address,name
0,23100000000000000000000001,"41066 Smith Forge Suite 996 Port Tonyville, NM...",Timothy Harris
1,38100000000000000000000037,"40153 Jackson Shoal Suite 500 Briantown, NY 17659",Ruben Smith
2,25100000000000000000000043,"51860 Cristian Forges Suite 287 Daniellebury, ...",Richard Calhoun
3,75100000000000000000000092,"2154 Shawn Harbor New Kristinview, HI 60798",Kathleen Davis
4,61100000000000000000000067,"654 Gallegos Squares Apt. 014 Milesland, NM 86375",Angela Thompson
5,29100000000000000000000032,"704 Pham Tunnel Caseyville, PA 34185",Andrew Sullivan
6,73100000000000000000000099,"PSC 7378, Box 2479 APO AA 22864",Carol Brown
7,37100000000000000000000065,"9537 Brandon Cliff Port Corychester, MT 94287",Robert Gonzalez
8,48100000000000000000000083,Unit 6070 Box 1597 DPO AP 99301,Thomas Gonzalez
9,21100000000000000000000086,"73469 Michael Extensions Suite 775 New David, ...",Clinton Mccoy
10,73100000000000000000000086,"670 Castro Circles Lake Johnathan, CA 77878",Richard Kidd
11,25100000000000000000000009,"39744 Wright Camp Thomaston, MT 43282",Jonathon Pope
12,35100000000000000000000001,"12099 Wiggins Rue Apt. 716 South Kaylamouth, M...",Tracy Dean
13,94100000000000000000000011,"079 Deborah Lane Suite 181 North Tammymouth, T...",Beth Campos
14,33100000000000000000000098,"9201 Morgan Station Suite 951 Port Jamesport, ...",Steven Padilla
15,98100000000000000000000044,"0990 Rojas Gardens Apt. 102 Jonesfort, FL 19038",Pamela Haynes
16,63100000000000000000000074,"21665 Derek Parkway Christychester, MA 13772",Roy Elliott
17,91100000000000000000000074,"4694 Alison Crest Apt. 757 Davidstad, ND 84301",Dr. Barbara Jones
18,95100000000000000000000051,"929 Mary Square Suite 587 Erinport, ID 51319",Robert Stephenson
19,48100000000000000000000024,"71378 Rachel Lakes Richardsfurt, VT 57450",Mark Castillo
20,82100000000000000000000051,"41485 Brian Estates Suite 650 Theresatown, TX ...",Leslie Jackson
21,64100000000000000000000045,"7162 Hendrix Inlet Ewinghaven, LA 47468",George Herrera
22,44100000000000000000000024,"49879 Julie Expressway Sarahton, WV 94733",Thomas Gutierrez
23,23100000000000000000000073,"82168 Steven Summit Suite 359 East Paulbury, M...",Michael Glover
24,67100000000000000000000072,"4433 Elliott Shoal Port Andrea, TN 96454",Cassandra Hart
25,73100000000000000000000057,"194 Joseph Isle Graveston, TN 59269",Richard Simmons
26,22100000000000000000000010,"206 Arnold Shore Suite 749 Fisherport, VT 08176",Brian Smith Jr.
27,37100000000000000000000047,"580 Martinez Green Apt. 816 Jessicafort, PA 02556",Elizabeth Jones
28,50100000000000000000000008,"PSC 9962, Box 4342 APO AA 02490",Brendan Mills
29,18100000000000000000000061,Unit 9693 Box 1296 DPO AA 33367,Johnathan Alvarez
...,...,...,...
914,28100000000000000000000029,"427 Ronald Brook New Brandonport, AK 82954",Evan Stevenson
915,97100000000000000000000057,"7682 Lamb Plains Apt. 761 Chavezchester, IA 57081",Danny Shah
916,44100000000000000000000068,"30781 Wilson Fort Suite 902 Martinezburgh, ME ...",Mary Fox
917,68100000000000000000000072,"4584 Joel Knoll Nathanshire, AR 41893",Matthew Jones
918,32100000000000000000000089,"9600 Michael Forest Lake Tonyabury, KY 77176",Ebony Jackson
919,95100000000000000000000012,"400 Brooks Branch East Allisonburgh, VA 45134",David Rasmussen
920,79100000000000000000000058,"76473 James Isle Suite 596 Bethburgh, TX 38167",Lisa Johnston
921,60100000000000000000000044,"PSC 0535, Box 1141 APO AE 32690",Amanda Paul
922,22100000000000000000000041,"506 Ho Shores Patriciabury, SC 65478",Elizabeth Turner
923,95100000000000000000000023,"1777 Blake Gardens New Edward, NE 37459",Samantha Taylor
924,47100000000000000000000092,"2257 Brooks Mount West Rebecca, ME 50273",Brian Davila
925,91100000000000000000000038,"04862 Long Roads Apt. 331 North Zoe, WI 78886",Brandon Miller
926,18100000000000000000000096,"39300 Heather Motorway East Matthew, WV 43819",William Bowman
927,24100000000000000000000070,"53628 Sullivan Knolls Lake Gregorymouth, WA 12978",Catherine Potter
928,92100000000000000000000039,"3755 Kathryn Plains Apt. 968 East Cameronfort,...",Heather Rodriguez
929,66100000000000000000000028,"27506 Hernandez Mills West Adrienneshire, NJ 7...",Kaitlyn Oneal
930,78100000000000000000000011,"383 Aaron Village Apt. 348 Daviston, VA 63143",Christina Thompson
931,83100000000000000000000005,"9034 Carolyn Rest Suite 797 Peterland, LA 38894",Mary Garcia
932,10100000000000000000000073,"65526 Mitchell Landing Tuckerport, CA 56583",Jacqueline Blake
933,16100000000000000000000018,"7652 Kyle Street Wallston, CT 36722",Tyler Ward
934,25100000000000000000000030,"94465 Andrew Drives South Davidfort, MN 36885",Laura Brock
935,11100000000000000000000080,"50607 Lee Rapid South Donald, WV 79182",Brian Henry
936,93100000000000000000000042,"3147 Cummings Forks Apt. 858 Lake Alexandra, O...",Mr. John Mejia
937,14100000000000000000000052,"476 Jeanne Summit Crystalbury, WV 89672",Kenneth Aguilar
938,48100000000000000000000080,"213 Shannon Spring South John, UT 59800",Justin Hart
939,14100000000000000000000049,"6270 Eric Tunnel Leebury, WI 53197",Cynthia Dillon
940,98100000000000000000000055,"04500 Brandt Corner Davidmouth, IA 25881",Jacqueline Kim
941,15100000000000000000000072,"057 Rebecca Rue Suite 928 Tammyborough, SD 53701",Julie Austin
942,91100000000000000000000079,"38962 Herring Court Suite 841 Millermouth, WA ...",Rebecca Perry
943,40100000000000000000000062,"909 Lindsey Fields Port Michelle, AK 76616",Christina Adams

In [9]:
transformed_meter_data = sqlContext.read.format("org.apache.spark.sql.cassandra").options(table="meter_data", keyspace="tangez_transformed").load()
transformed_meter_data.toPandas()

,meter_data_id,checksum,consumption_data,encoder_tamper,ert_id,ert_id_ls_bits,ert_id_ms_bits,ert_type,physical_tamper,preamble,received_ts,reserved,sync_bit
0,72563,47498238489494848,969,None,72100000000000000000000070,100000000000000000000070,72,electric,None,0xF2A60,2018-12-28 11:45:06,None,1
1,89726,47498238489494848,1871,None,89100000000000000000000021,100000000000000000000021,89,electric,None,0xF2A60,2018-12-28 11:45:06,None,1
2,15533,47498238489494848,1716,None,15100000000000000000000081,100000000000000000000081,15,electric,None,0xF2A60,2018-12-28 11:45:06,None,1
3,54740,47498238489494848,932,None,54100000000000000000000091,100000000000000000000091,54,electric,None,0xF2A60,2018-12-28 11:45:06,None,1
4,50209,47498238489494848,3968,None,50100000000000000000000001,100000000000000000000001,50,electric,None,0xF2A60,2018-12-28 11:30:05,None,1
5,46640,47498238489494848,1890,None,46100000000000000000000035,100000000000000000000035,46,electric,None,0xF2A60,2018-12-28 11:30:05,None,1
6,50442,47498238489494848,3230,None,50100000000000000000000042,100000000000000000000042,50,electric,None,0xF2A60,2018-12-28 11:45:06,None,1
7,3022,47498238489494848,1830,None,30100000000000000000000062,100000000000000000000062,30,electric,None,0xF2A60,2018-12-28 11:15:03,None,1
8,71306,47498238489494848,3149,None,71100000000000000000000063,100000000000000000000063,71,electric,None,0xF2A60,2018-12-28 11:45:06,None,1
9,62135,47498238489494848,3989,None,62100000000000000000000066,100000000000000000000066,62,electric,None,0xF2A60,2018-12-28 11:45:06,None,1
10,27560,47498238489494848,2250,None,27100000000000000000000011,100000000000000000000011,27,electric,None,0xF2A60,2018-12-28 11:45:06,None,1
11,63565,47498238489494848,3922,None,63100000000000000000000053,100000000000000000000053,63,electric,None,0xF2A60,2018-12-28 11:30:05,None,1
12,69507,47498238489494848,2261,None,69100000000000000000000004,100000000000000000000004,69,electric,None,0xF2A60,2018-12-28 11:00:45,None,1
13,54374,47498238489494848,2257,None,54100000000000000000000080,100000000000000000000080,54,electric,None,0xF2A60,2018-12-28 11:45:06,None,1
14,60813,47498238489494848,2139,None,60100000000000000000000076,100000000000000000000076,60,electric,None,0xF2A60,2018-12-28 11:30:05,None,1
15,20862,47498238489494848,3188,None,20100000000000000000000069,100000000000000000000069,20,electric,None,0xF2A60,2018-12-28 11:00:45,None,1
16,69451,47498238489494848,415,None,69100000000000000000000013,100000000000000000000013,69,electric,None,0xF2A60,2018-12-28 11:00:45,None,1
17,63367,47498238489494848,2772,None,63100000000000000000000005,100000000000000000000005,63,electric,None,0xF2A60,2018-12-28 11:00:45,None,1
18,48823,47498238489494848,3783,None,48100000000000000000000039,100000000000000000000039,48,electric,None,0xF2A60,2018-12-28 11:45:06,None,1
19,67824,47498238489494848,1123,None,67100000000000000000000095,100000000000000000000095,67,electric,None,0xF2A60,2018-12-28 11:00:45,None,1
20,98953,47498238489494848,3815,None,98100000000000000000000096,100000000000000000000096,98,electric,None,0xF2A60,2018-12-28 11:00:45,None,1
21,41277,47498238489494848,3677,None,41100000000000000000000060,100000000000000000000060,41,electric,None,0xF2A60,2018-12-28 11:15:03,None,1
22,94605,47498238489494848,2634,None,94100000000000000000000091,100000000000000000000091,94,electric,None,0xF2A60,2018-12-28 11:30:05,None,1
23,7072,47498238489494848,515,None,70100000000000000000000056,100000000000000000000056,70,electric,None,0xF2A60,2018-12-28 11:00:45,None,1
24,95988,47498238489494848,3561,None,95100000000000000000000040,100000000000000000000040,95,electric,None,0xF2A60,2018-12-28 11:00:45,None,1
25,12376,47498238489494848,1964,None,12100000000000000000000035,100000000000000000000035,12,electric,None,0xF2A60,2018-12-28 11:45:06,None,1
26,25604,47498238489494848,696,None,25100000000000000000000043,100000000000000000000043,25,electric,None,0xF2A60,2018-12-28 11:30:05,None,1
27,92839,47498238489494848,2663,None,92100000000000000000000029,100000000000000000000029,92,electric,None,0xF2A60,2018-12-28 11:15:03,None,1
28,89487,47498238489494848,2980,None,89100000000000000000000010,100000000000000000000010,89,electric,None,0xF2A60,2018-12-28 11:30:05,None,1
29,1135,47498238489494848,2564,None,11100000000000000000000001,100000000000000000000001,11,electric,None,0xF2A60,2018-12-28 11:00:45,None,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3889,67114,47498238489494848,1143,None,67100000000000000000000087,100000000000000000000087,67,electric,None,0xF2A60,2018-12-28 11:30:05,None,1
3890,41413,47498238489494848,1337,None,41100000000000000000000014,100000000000000000000014,41,electric,None,0xF2A60,2018-12-28 11:30:05,None,1
3891,36361,47498238489494848,3610,None,36100000000000000000000094,100000000000000000000094,36,electric,None,0xF2A60,2018-12-28 11:00:45,None,1
3892,33140,47498238489494848,2309,None,33100000000000000000000062,100000000000000000000062,33,electric,None,0xF2A60,2018-12-28 11:00:45,None,1
3893,40735,47498238489494848,850,None,40100000000000000000000023,100000000000000000000023,40,electric,None,0xF2A60,2018-12-28 11:15:03,None,1
3894,80624,47498238489494848,1864,None,80100000000000000000000024,100000000000000000000024,80,electric,None,0xF2A60,2018-12-28 11:00:45,None,1
3895,97917,47498238489494848,2701,None,97100000000000000000000020,100000000000000000000020,97,electric,None,0xF2A60,2018-12-28 11:15:03,None,1
3896,71545,47498238489494848,1171,None,71100000000000000000000036,100000000000000000000036,71,electric,None,0xF2A60,2018-12-28 11:15:03,None,1
3897,6642,47498238489494848,1687,None,66100000000000000000000031,100000000000000000000031,66,electric,None,0xF2A60,2018-12-28 11:00:45,None,1
3898,4219,47498238489494848,1783,None,42100000000000000000000072,100000000000000000000072,42,electric,None,0xF2A60,2018-12-28 11:30:05,None,1
3899,44836,47498238489494848,2038,None,44100000000000000000000055,100000000000000000000055,44,electric,None,0xF2A60,2018-12-28 11:00:45,None,1
3900,55480,47498238489494848,2935,None,55100000000000000000000070,100000000000000000000070,55,electric,None,0xF2A60,2018-12-28 11:00:45,None,1
3901,5266,47498238489494848,736,None,52100000000000000000000038,100000000000000000000038,52,electric,None,0xF2A60,2018-12-28 11:00:45,None,1
3902,69257,47498238489494848,1854,None,69100000000000000000000043,100000000000000000000043,69,electric,None,0xF2A60,2018-12-28 11:30:05,None,1
3903,68143,47498238489494848,3633,None,68100000000000000000000013,100000000000000000000013,68,electric,None,0xF2A60,2018-12-28 11:00:45,None,1
3904,75308,47498238489494848,531,None,75100000000000000000000014,100000000000000000000014,75,electric,None,0xF2A60,2018-12-28 11:00:45,None,1
3905,92669,47498238489494848,1408,None,92100000000000000000000083,100000000000000000000083,92,electric,None,0xF2A60,2018-12-28 11:15:03,None,1
3906,22820,47498238489494848,860,None,22100000000000000000000032,100000000000000000000032,22,electric,None,0xF2A60,2018-12-28 11:00:45,None,1
3907,29314,47498238489494848,333,None,29100000000000000000000064,100000000000000000000064,29,electric,None,0xF2A60,2018-12-28 11:00:45,None,1
3908,23980,47498238489494848,1108,None,23100000000000000000000082,100000000000000000000082,23,electric,None,0xF2A60,2018-12-28 11:30:05,None,1
3909,34974,47498238489494848,3537,None,34100000000000000000000097,100000000000000000000097,34,electric,None,0xF2A60,2018-12-28 11:30:05,None,1
3910,54511,47498238489494848,1711,None,54100000000000000000000025,100000000000000000000025,54,electric,None,0xF2A60,2018-12-28 11:45:06,None,1
3911,89581,47498238489494848,1163,None,89100000000000000000000020,100000000000000000000020,89,electric,None,0xF2A60,2018-12-28 11:00:45,None,1
3912,77917,47498238489494848,3384,None,77100000000000000000000077,100000000000000000000077,77,electric,None,0xF2A60,2018-12-28 11:30:05,None,1
3913,88512,47498238489494848,2955,None,88100000000000000000000057,100000000000000000000057,88,electric,None,0xF2A60,2018-12-28 11:45:06,None,1
3914,63412,47498238489494848,2319,None,63100000000000000000000023,100000000000000000000023,63,electric,None,0xF2A60,2018-12-28 11:30:05,None,1
3915,1683,47498238489494848,536,None,16100000000000000000000099,100000000000000000000099,16,electric,None,0xF2A60,2018-12-28 11:45:06,None,1
3916,31975,47498238489494848,605,None,31100000000000000000000014,100000000000000000000014,31,electric,None,0xF2A60,2018-12-28 11:45:06,None,1
3917,58355,47498238489494848,2650,None,58100000000000000000000073,100000000000000000000073,58,electric,None,0xF2A60,2018-12-28 11:00:45,None,1
3918,55787,47498238489494848,3690,None,55100000000000000000000087,100000000000000000000087,55,electric,None,0xF2A60,2018-12-28 11:00:45,None,1

In [2]:
joined_data = sqlContext.read.format("org.apache.spark.sql.cassandra").options(table="meter_customer_data", keyspace="tangez_transformed").load()
joined_data.toPandas()

,meter_data_id,address,checksum,consumption_data,encoder_tamper,ert_id,ert_id_ls_bits,ert_id_ms_bits,ert_type,name,physical_tamper,preamble,received_ts,reserved,sync_bit
0,82233,"41485 Brian Estates Suite 650 Theresatown, TX ...",47498238489494848,2879,None,82100000000000000000000051,100000000000000000000051,82,electric,Leslie Jackson,None,0xF2A60,2018-12-28 11:45:39,None,1
1,4640,"PSC 6783, Box 6839 APO AP 30006",47498238489494848,2055,None,46100000000000000000000061,100000000000000000000061,46,electric,James Weber,None,0xF2A60,2018-12-28 11:00:17,None,1
2,61389,USNV Jackson FPO AP 40458,47498238489494848,2141,None,61100000000000000000000084,100000000000000000000084,61,electric,Melissa Mitchell,None,0xF2A60,2018-12-28 11:00:17,None,1
3,75287,"833 Jodi Circles South Stevenville, OK 95345",47498238489494848,141,None,75100000000000000000000048,100000000000000000000048,75,electric,James Wilson,None,0xF2A60,2018-12-28 11:15:34,None,1
4,48645,"55448 James Ridges Suite 523 Port Danastad, WA...",47498238489494848,1547,None,48100000000000000000000017,100000000000000000000017,48,electric,Travis Smith,None,0xF2A60,2018-12-28 11:30:37,None,1
5,56285,"5099 Pamela Roads North Jason, CA 23251",47498238489494848,1690,None,56100000000000000000000011,100000000000000000000011,56,electric,Maurice Mathis,None,0xF2A60,2018-12-28 11:45:39,None,1
6,68307,"73192 Mcpherson Extension Mitchellberg, GA 46689",47498238489494848,3445,None,68100000000000000000000062,100000000000000000000062,68,electric,Jose Hicks,None,0xF2A60,2018-12-28 11:30:37,None,1
7,73822,"PSC 7378, Box 2479 APO AA 22864",47498238489494848,3864,None,73100000000000000000000099,100000000000000000000099,73,electric,Carol Brown,None,0xF2A60,2018-12-28 11:15:34,None,1
8,66820,"48324 Farley Club South Stevenport, OR 13613",47498238489494848,1129,None,66100000000000000000000099,100000000000000000000099,66,electric,Kim Santiago,None,0xF2A60,2018-12-28 11:15:34,None,1
9,46129,"98879 Elizabeth Gardens Davisside, CA 94818",47498238489494848,861,None,46100000000000000000000007,100000000000000000000007,46,electric,Steven Walton,None,0xF2A60,2018-12-28 11:00:17,None,1
10,61215,"5132 Brewer Cliff Port Josephville, MS 20031",47498238489494848,2803,None,61100000000000000000000052,100000000000000000000052,61,electric,Mrs. Laura Goodwin,None,0xF2A60,2018-12-28 11:15:34,None,1
11,58859,"75164 Tyler Ports Suite 876 North Sabrina, WY ...",47498238489494848,1725,None,58100000000000000000000035,100000000000000000000035,58,electric,Juan Guzman,None,0xF2A60,2018-12-28 11:00:17,None,1
12,59983,"36901 Stephanie Pass Apt. 715 Arnoldshire, VA ...",47498238489494848,2241,None,59100000000000000000000056,100000000000000000000056,59,electric,Tonya Sweeney,None,0xF2A60,2018-12-28 11:45:39,None,1
13,39776,"455 Frey Glens West Cristina, NH 51746",47498238489494848,2223,None,39100000000000000000000031,100000000000000000000031,39,electric,Tammy Griffin,None,0xF2A60,2018-12-28 11:30:37,None,1
14,90567,"8880 Amanda Ports Whitemouth, PA 02864",47498238489494848,3009,None,90100000000000000000000010,100000000000000000000010,90,electric,Dana Torres,None,0xF2A60,2018-12-28 11:45:39,None,1
15,5612,"5099 Pamela Roads North Jason, CA 23251",47498238489494848,1674,None,56100000000000000000000011,100000000000000000000011,56,electric,Maurice Mathis,None,0xF2A60,2018-12-28 11:45:39,None,1
16,39780,"62254 Wade Mills Avilaton, AZ 82102",47498238489494848,842,None,39100000000000000000000018,100000000000000000000018,39,electric,Katie Garcia,None,0xF2A60,2018-12-28 11:00:17,None,1
17,27387,"930 Moreno Ways Suite 184 East Nathan, WA 88693",47498238489494848,3343,None,27100000000000000000000069,100000000000000000000069,27,electric,Todd Miller,None,0xF2A60,2018-12-28 11:00:17,None,1
18,26956,"PSC 3179, Box 5629 APO AP 81817",47498238489494848,2989,None,26100000000000000000000014,100000000000000000000014,26,electric,Steven Glover,None,0xF2A60,2018-12-28 11:30:37,None,1
19,65456,"9715 Kelley Brooks Suite 884 East Brian, TN 95151",47498238489494848,2274,None,65100000000000000000000013,100000000000000000000013,65,electric,Nicholas Keith,None,0xF2A60,2018-12-28 11:00:17,None,1
20,75222,USCGC Ward FPO AE 44581,47498238489494848,1813,None,75100000000000000000000050,100000000000000000000050,75,electric,Nathan Blair,None,0xF2A60,2018-12-28 11:00:17,None,1
21,54596,"639 Jake Mount Suite 936 North Jessicafort, UT...",47498238489494848,2377,None,54100000000000000000000091,100000000000000000000091,54,electric,Kristen Williams,None,0xF2A60,2018-12-28 11:45:39,None,1
22,51895,"06235 Rogers Bypass Apt. 034 Port John, MA 81473",47498238489494848,3134,None,51100000000000000000000000,100000000000000000000000,51,electric,Keith Morris,None,0xF2A60,2018-12-28 11:45:39,None,1
23,74248,"6129 Carson Junction South George, CT 44987",47498238489494848,3185,None,74100000000000000000000011,100000000000000000000011,74,electric,Christina Blevins,None,0xF2A60,2018-12-28 11:15:34,None,1
24,88408,"716 Michael Forge Suite 226 Wheelertown, OR 11438",47498238489494848,2665,None,88100000000000000000000061,100000000000000000000061,88,electric,Natalie Rodriguez,None,0xF2A60,2018-12-28 11:00:17,None,1
25,49553,"5957 Buchanan Points West Diane, AK 16313",47498238489494848,2735,None,49100000000000000000000000,100000000000000000000000,49,electric,Todd Henry,None,0xF2A60,2018-12-28 11:00:17,None,1
26,66248,"18650 Ana Shoal Apt. 643 New Heather, ID 61056",47498238489494848,2589,None,66100000000000000000000036,100000000000000000000036,66,electric,Kara Hughes,None,0xF2A60,2018-12-28 11:45:39,None,1
27,48600,"265 Jennifer Pike South Randy, AZ 78123",47498238489494848,1506,None,48100000000000000000000019,100000000000000000000019,48,electric,Stephanie Hall,None,0xF2A60,2018-12-28 11:45:39,None,1
28,16690,USNV Hood FPO AE 26723,47498238489494848,632,None,16100000000000000000000035,100000000000000000000035,16,electric,Billy Perez,None,0xF2A60,2018-12-28 11:45:39,None,1
29,71877,"61250 Tucker Garden Suite 731 Dodsonshire, MD ...",47498238489494848,1884,None,71100000000000000000000081,100000000000000000000081,71,electric,Jennifer Bridges,None,0xF2A60,2018-12-28 11:45:39,None,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
362,51423,"4314 Johnson Plains Hernandezmouth, MT 95407",47498238489494848,2905,None,51100000000000000000000087,100000000000000000000087,51,electric,Courtney Le,None,0xF2A60,2018-12-28 11:15:34,None,1
363,62154,"079 Ross Path New Kaitlynfurt, IN 22587",47498238489494848,3956,None,62100000000000000000000072,100000000000000000000072,62,electric,Charles White,None,0xF2A60,2018-12-28 11:45:39,None,1
364,56146,"77689 Rowland Forge Quinnborough, AL 24096",47498238489494848,622,None,56100000000000000000000046,100000000000000000000046,56,electric,John Stewart,None,0xF2A60,2018-12-28 11:45:39,None,1
365,83676,Unit 9875 Box 3046 DPO AA 00781,47498238489494848,3095,None,83100000000000000000000016,100000000000000000000016,83,electric,William Morales,None,0xF2A60,2018-12-28 11:00:17,None,1
366,43524,"4452 Owens Skyway East Mark, MN 51681",47498238489494848,3053,None,43100000000000000000000050,100000000000000000000050,43,electric,Sean Underwood,None,0xF2A60,2018-12-28 11:30:37,None,1
367,52485,"52560 Gonzalez Burg Suite 866 Edwardbury, IA 2...",47498238489494848,3604,None,52100000000000000000000049,100000000000000000000049,52,electric,Kelly Hall,None,0xF2A60,2018-12-28 11:00:17,None,1
368,32751,"186 Casey Knolls Danielland, WI 58517",47498238489494848,3994,None,32100000000000000000000083,100000000000000000000083,32,electric,Brandi Cook,None,0xF2A60,2018-12-28 11:00:17,None,1
369,66903,"27506 Hernandez Mills West Adrienneshire, NJ 7...",47498238489494848,1706,None,66100000000000000000000028,100000000000000000000028,66,electric,Kaitlyn Oneal,None,0xF2A60,2018-12-28 11:45:39,None,1
370,2434,"332 Lynn Crest Ayalaville, MA 94894",47498238489494848,2365,None,24100000000000000000000100,100000000000000000000100,24,electric,April Peterson,None,0xF2A60,2018-12-28 11:15:34,None,1
371,86782,"5889 Simmons Prairie Suite 058 Colemanburgh, V...",47498238489494848,1567,None,86100000000000000000000010,100000000000000000000010,86,electric,Tonya Johnson,None,0xF2A60,2018-12-28 11:00:17,None,1
372,47965,"428 Stephen Port Apt. 347 East David, NY 08590",47498238489494848,3385,None,47100000000000000000000096,100000000000000000000096,47,electric,Barbara Hobbs,None,0xF2A60,2018-12-28 11:15:34,None,1
373,56593,"7255 Christine Branch South Raymondbury, NY 68153",47498238489494848,449,None,56100000000000000000000050,100000000000000000000050,56,electric,Adam Pena,None,0xF2A60,2018-12-28 11:15:34,None,1
374,95550,"882 Julie Squares Apt. 802 Gonzalezville, WV 2...",47498238489494848,588,None,95100000000000000000000095,100000000000000000000095,95,electric,Guy Ritter,None,0xF2A60,2018-12-28 11:45:39,None,1
375,55914,"8306 Miller Dam Suttonburgh, NH 36474",47498238489494848,3952,None,55100000000000000000000051,100000000000000000000051,55,electric,Benjamin Caldwell,None,0xF2A60,2018-12-28 11:45:39,None,1
376,9211,"3755 Kathryn Plains Apt. 968 East Cameronfort,...",47498238489494848,1518,None,92100000000000000000000039,100000000000000000000039,92,electric,Heather Rodriguez,None,0xF2A60,2018-12-28 11:45:39,None,1
377,81210,"7685 Laura Centers Davidmouth, MI 69801",47498238489494848,739,None,81100000000000000000000045,100000000000000000000045,81,electric,Ricky Jacobs,None,0xF2A60,2018-12-28 11:45:39,None,1
378,49578,Unit 1872 Box 1075 DPO AP 81637,47498238489494848,3211,None,49100000000000000000000098,100000000000000000000098,49,electric,Mike Hughes,None,0xF2A60,2018-12-28 11:15:34,None,1
379,61450,"8943 Sanders Mountain Irwinmouth, AR 83900",47498238489494848,1437,None,61100000000000000000000019,100000000000000000000019,61,electric,Brian Smith,None,0xF2A60,2018-12-28 11:00:17,None,1
380,11313,"811 Burke Avenue Apt. 401 Frazierstad, AZ 97737",47498238489494848,2400,None,11100000000000000000000047,100000000000000000000047,11,electric,Jessica Ramirez,None,0xF2A60,2018-12-28 11:45:39,None,1
381,56560,"274 Conway Passage Apt. 669 North Kenneth, MI ...",47498238489494848,2302,None,56100000000000000000000035,100000000000000000000035,56,electric,Christopher Robinson,None,0xF2A60,2018-12-28 11:15:34,None,1
382,3229,"5386 Sampson Pine Valerieberg, CT 19671",47498238489494848,1952,None,32100000000000000000000072,100000000000000000000072,32,electric,Peter Johnson,None,0xF2A60,2018-12-28 11:00:17,None,1
383,11698,"934 William Manor East Sophiamouth, ME 72902",47498238489494848,2193,None,11100000000000000000000072,100000000000000000000072,11,electric,Thomas Elliott,None,0xF2A60,2018-12-28 11:15:34,None,1
384,65651,"PSC 0983, Box 0805 APO AP 80517",47498238489494848,1093,None,65100000000000000000000064,100000000000000000000064,65,electric,Mark Johnson,None,0xF2A60,2018-12-28 11:30:37,None,1
385,75910,"4138 Jeremiah Courts Apt. 573 New Matthew, VT ...",47498238489494848,1465,None,75100000000000000000000005,100000000000000000000005,75,electric,Courtney Torres,None,0xF2A60,2018-12-28 11:45:39,None,1
386,74653,"8921 Michael Mission Apt. 857 Port Olivia, NE ...",47498238489494848,2046,None,74100000000000000000000076,100000000000000000000076,74,electric,Jeffrey Miller,None,0xF2A60,2018-12-28 11:45:39,None,1
387,68449,"4369 Cooper Terrace Apt. 547 Lake Bryanview, M...",47498238489494848,1449,None,68100000000000000000000096,100000000000000000000096,68,electric,Rick Harmon,None,0xF2A60,2018-12-28 11:00:17,None,1
388,87798,"98286 Lisa Harbors Port Nathaniel, UT 80534",47498238489494848,474,None,87100000000000000000000051,100000000000000000000051,87,electric,Latoya Ramos,None,0xF2A60,2018-12-28 11:15:34,None,1
389,55480,"5963 David Courts Suite 967 Port Ericland, IA ...",47498238489494848,2935,None,55100000000000000000000070,100000000000000000000070,55,electric,Lindsey Johnson,None,0xF2A60,2018-12-28 11:00:17,None,1
390,89581,"04442 Smith Rapid Apt. 393 Port Matthew, ID 48648",47498238489494848,1163,None,89100000000000000000000020,100000000000000000000020,89,electric,Catherine Morris,None,0xF2A60,2018-12-28 11:00:17,None,1
391,58355,"PSC 2578, Box 9009 APO AP 51679",47498238489494848,2650,None,58100000000000000000000073,100000000000000000000073,58,electric,Cheyenne Austin,None,0xF2A60,2018-12-28 11:00:17,None,1

In [3]:
dm_15_min_sum = sqlContext.read.format("org.apache.spark.sql.cassandra").options(table="consumption_15_minutes_sum", keyspace="tangez_data_marts").load()
dm_15_min_sum.toPandas()

                         ert_id  consumption_data_sum         received_ts
0    86100000000000000000000056                  3721 2018-12-28 11:45:00
1    89100000000000000000000010                  2980 2018-12-28 11:30:00
2    66100000000000000000000036                  2589 2018-12-28 11:45:00
3    74100000000000000000000017                  3327 2018-12-28 11:45:00
4    74100000000000000000000011                  3185 2018-12-28 11:15:00
5    10100000000000000000000035                   422 2018-12-28 11:15:00
6    19100000000000000000000070                  3055 2018-12-28 11:00:00
7    73100000000000000000000017                  2754 2018-12-28 11:30:00
8    91100000000000000000000067                   555 2018-12-28 11:00:00
9    42100000000000000000000022                   573 2018-12-28 11:15:00
10   65100000000000000000000046                  2986 2018-12-28 11:15:00
11   96100000000000000000000055                  1142 2018-12-28 11:30:00
12   66100000000000000000000056                  1242 2018-12-28 11:15:00
13   11100000000000000000000072                  2193 2018-12-28 11:15:00
14   24100000000000000000000022                  1660 2018-12-28 11:00:00
15   69100000000000000000000020                  3536 2018-12-28 11:30:00
16   84100000000000000000000045                   962 2018-12-28 11:15:00
17   35100000000000000000000071                  2135 2018-12-28 11:45:00
18   38100000000000000000000016                  2810 2018-12-28 11:00:00
19   23100000000000000000000042                  3945 2018-12-28 11:15:00
20   89100000000000000000000073                  1896 2018-12-28 11:45:00
21   14100000000000000000000056                  2598 2018-12-28 11:15:00
22   88100000000000000000000061                  6337 2018-12-28 11:15:00
23   84100000000000000000000072                  3417 2018-12-28 11:30:00
24   65100000000000000000000008                  1073 2018-12-28 11:30:00
25   17100000000000000000000003                   538 2018-12-28 11:45:00
26   82100000000000000000000080                  2092 2018-12-28 11:45:00
27   61100000000000000000000009                  3125 2018-12-28 11:45:00
28   72100000000000000000000082                  2596 2018-12-28 11:15:00
29   98100000000000000000000026                  2450 2018-12-28 11:30:00
..                          ...                   ...                 ...
297  29100000000000000000000014                  1895 2018-12-28 11:15:00
298  39100000000000000000000018                   842 2018-12-28 11:00:00
299  89100000000000000000000020                  1163 2018-12-28 11:00:00
300  53100000000000000000000020                   808 2018-12-28 11:00:00
301  25100000000000000000000082                   208 2018-12-28 11:45:00
302  44100000000000000000000100                   296 2018-12-28 11:00:00
303  80100000000000000000000069                   555 2018-12-28 11:00:00
304  29100000000000000000000054                  3339 2018-12-28 11:30:00
305  44100000000000000000000019                   704 2018-12-28 11:15:00
306  52100000000000000000000074                   603 2018-12-28 11:45:00
307  61100000000000000000000072                  3788 2018-12-28 11:00:00
308  75100000000000000000000005                  1465 2018-12-28 11:45:00
309  13100000000000000000000080                  2478 2018-12-28 11:15:00
310  72100000000000000000000097                  2137 2018-12-28 11:00:00
311  17100000000000000000000032                   206 2018-12-28 11:15:00
312  41100000000000000000000009                  3977 2018-12-28 11:15:00
313  15100000000000000000000058                   694 2018-12-28 11:15:00
314  24100000000000000000000019                  1993 2018-12-28 11:30:00
315  92100000000000000000000073                  3410 2018-12-28 11:00:00
316  82100000000000000000000081                  1978 2018-12-28 11:45:00
317  28100000000000000000000029                  2852 2018-12-28 11:45:00
318  79100000000000000000000058                  1888 2018-12-28 11:15:00
319  22100000000000000000000041                  1526 2018-12-28 11:15:00
320  47100000000000000000000092                  1794 2018-12-28 11:15:00
321  18100000000000000000000096                   583 2018-12-28 11:45:00
322  24100000000000000000000070                  2938 2018-12-28 11:30:00
323  92100000000000000000000039                  1518 2018-12-28 11:45:00
324  66100000000000000000000028                  1706 2018-12-28 11:45:00
325  10100000000000000000000073                  2814 2018-12-28 11:00:00
326  93100000000000000000000042                  2440 2018-12-28 11:30:00

[327 rows x 3 columns]

In [4]:
dm_1_hr_sum = sqlContext.read.format("org.apache.spark.sql.cassandra").options(table="consumption_1_hour_sum", keyspace="tangez_data_marts").load()
dm_1_hr_sum.toPandas()

                         ert_id  consumption_data_sum start_of_hour_time
0    86100000000000000000000056                  3721               None
1    89100000000000000000000010                  4614               None
2    66100000000000000000000036                  2589               None
3    74100000000000000000000017                  3327               None
4    74100000000000000000000011                  3185               None
5    10100000000000000000000035                   422               None
6    19100000000000000000000070                  3055               None
7    73100000000000000000000017                  2754               None
8    91100000000000000000000067                   555               None
9    42100000000000000000000022                   573               None
10   65100000000000000000000046                  2986               None
11   96100000000000000000000055                  1142               None
12   66100000000000000000000056                  1242               None
13   11100000000000000000000072                  2193               None
14   24100000000000000000000022                  1660               None
15   69100000000000000000000020                  3536               None
16   84100000000000000000000045                   962               None
17   35100000000000000000000071                  2840               None
18   38100000000000000000000016                  2810               None
19   23100000000000000000000042                  3945               None
20   89100000000000000000000073                  1896               None
21   14100000000000000000000056                  2598               None
22   88100000000000000000000061                  9002               None
23   84100000000000000000000072                  3417               None
24   65100000000000000000000008                  1073               None
25   17100000000000000000000003                   538               None
26   82100000000000000000000080                  2092               None
27   61100000000000000000000009                  3125               None
28   72100000000000000000000082                  2596               None
29   98100000000000000000000026                  2450               None
..                          ...                   ...                ...
297  29100000000000000000000014                  1895               None
298  39100000000000000000000018                   842               None
299  89100000000000000000000020                  1163               None
300  53100000000000000000000020                   808               None
301  25100000000000000000000082                   208               None
302  44100000000000000000000100                   296               None
303  80100000000000000000000069                  2460               None
304  29100000000000000000000054                  3339               None
305  44100000000000000000000019                   704               None
306  52100000000000000000000074                   603               None
307  61100000000000000000000072                  3788               None
308  75100000000000000000000005                  1465               None
309  13100000000000000000000080                  2478               None
310  72100000000000000000000097                  2137               None
311  17100000000000000000000032                  3044               None
312  41100000000000000000000009                  3977               None
313  15100000000000000000000058                  3017               None
314  24100000000000000000000019                  1993               None
315  92100000000000000000000073                  3410               None
316  82100000000000000000000081                  5714               None
317  28100000000000000000000029                  6408               None
318  79100000000000000000000058                  1888               None
319  22100000000000000000000041                  1526               None
320  47100000000000000000000092                  1794               None
321  18100000000000000000000096                   583               None
322  24100000000000000000000070                  2938               None
323  92100000000000000000000039                  1518               None
324  66100000000000000000000028                  1706               None
325  10100000000000000000000073                  2814               None
326  93100000000000000000000042                  2440               None

[327 rows x 3 columns]